### ISSUE TITLE
There is a bug in iterateChildren function

### ISSUE THREAD

**Issue by mkleanthous** [vdomah/octoroles#3]
When true the iterator continues to search for the rest of the children with the problem that the last children might be "false" in the permission check although a previous one was true

To fix the problem I changed the code as follows:
    public static function iterateChildren($children, $perm)
    {
        $out = false;

        foreach ($children as $child) {
            if ($child->id == $perm->role_id) {
                $out = true;
            } elseif ($child->children != null) {
                $out = self::iterateChildren($child->children, $perm);
            }
            if ($out)
                return $out;
        }

        return $out;
    }

adding a check at the end of each iteration if the $out value is true to return it.

        return $out;
    }

**Comment by vdomah** [comment]
Thanks, added fix in new version 1.3.7
